export const SLUG_ISO: Record<string, string> = {
  tokyo: "JP", osaka: "JP", kyoto: "JP", fukuoka: "JP", sapporo: "JP",
  okinawa: "JP", nagoya: "JP",
  bangkok: "TH", chiangmai: "TH", phuket: "TH",
  hochiminh: "VN", hanoi: "VN", danang: "VN",
  singapore: "SG",
  bali: "ID",
  cebu: "PH", manila: "PH",
  kualalumpur: "MY", kotakinabalu: "MY",
  siemreap: "KH",
  taipei: "TW",
  hongkong: "HK",
  macau: "MO",
  shanghai: "CN", beijing: "CN",
  dubai: "AE",
  istanbul: "TR",
  maldives: "MV",
  paris: "FR",
  london: "GB",
  barcelona: "ES",
  rome: "IT",
  amsterdam: "NL",
  prague: "CZ",
  vienna: "AT",
  zurich: "CH",
  lisbon: "PT",
  athens: "GR",
  helsinki: "FI",
  newyork: "US", losangeles: "US", sanfrancisco: "US", lasvegas: "US",
  hawaii: "US",
  cancun: "MX",
  guam: "GU",
  saipan: "MP",
  sydney: "AU", melbourne: "AU",
  auckland: "NZ",
  cairo: "EG",
};

// Agoda city URL slug map — 공백 없는 lowercase, 특수 케이스
export const AGODA_CITY_SLUG: Record<string, string> = {
  tokyo: "tokyo", osaka: "osaka", kyoto: "kyoto", fukuoka: "fukuoka",
  sapporo: "sapporo", okinawa: "okinawa-jp", nagoya: "nagoya",
  bangkok: "bangkok", chiangmai: "chiang-mai", phuket: "phuket",
  hochiminh: "ho-chi-minh-city", hanoi: "hanoi", danang: "da-nang",
  singapore: "singapore",
  bali: "bali", cebu: "cebu", manila: "manila",
  kualalumpur: "kuala-lumpur", kotakinabalu: "kota-kinabalu",
  siemreap: "siem-reap",
  taipei: "taipei", hongkong: "hong-kong", macau: "macau",
  shanghai: "shanghai", beijing: "beijing",
  dubai: "dubai", istanbul: "istanbul", maldives: "maldives-islands",
  paris: "paris", london: "london", barcelona: "barcelona",
  rome: "rome", amsterdam: "amsterdam", prague: "prague",
  vienna: "vienna", zurich: "zurich", lisbon: "lisbon",
  athens: "athens", helsinki: "helsinki",
  newyork: "new-york-ny-us", losangeles: "los-angeles-ca-us",
  sanfrancisco: "san-francisco-ca-us", lasvegas: "las-vegas-nv-us",
  hawaii: "hawaii-us", cancun: "cancun",
  guam: "guam", saipan: "saipan",
  sydney: "sydney", melbourne: "melbourne", auckland: "auckland",
  cairo: "cairo",
};
