// slug → countryIso map (최소: POPULAR_SLUGS + curator/hero 지원 도시)
export const SLUG_ISO: Record<string, string> = {
  tokyo: "JP", osaka: "JP", kyoto: "JP", fukuoka: "JP", sapporo: "JP",
  okinawa: "JP", nagoya: "JP",
  bangkok: "TH", chiangmai: "TH", phuket: "TH",
  hochiminh: "VN", hanoi: "VN", danang: "VN",
  singapore: "SG",
  bali: "ID",
  cebu: "PH", manila: "PH",
  kualalumpur: "MY", kotakinabalu: "MY",
  siemreap: "KH",
  taipei: "TW",
  hongkong: "HK",
  macau: "MO",
  shanghai: "CN", beijing: "CN",
  dubai: "AE",
  istanbul: "TR",
  maldives: "MV",
  paris: "FR",
  london: "GB",
  barcelona: "ES",
  rome: "IT",
  amsterdam: "NL",
  prague: "CZ",
  vienna: "AT",
  zurich: "CH",
  lisbon: "PT",
  athens: "GR",
  helsinki: "FI",
  newyork: "US", losangeles: "US", sanfrancisco: "US", lasvegas: "US",
  hawaii: "US",
  cancun: "MX",
  guam: "GU",
  saipan: "MP",
  sydney: "AU", melbourne: "AU",
  auckland: "NZ",
  cairo: "EG",
};
